version: '3.7'
services:
  m9cad:
    container_name: m9cad
    image: m9cad:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
