# pull official base image
FROM node:14-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN apk --no-cache --virtual build-dependencies add \
        python \
        make \
        g++

# install app dependencies
COPY package*.json ./
RUN yarn install

RUN apk del build-dependencies

# add app
COPY . ./

# start app
CMD ["yarn", "start"]
